### ISSUE TITLE
[QAT] Update web3j version

### ISSUE THREAD

**Issue by ricardolyn** [ConsenSys/quorum-acceptance-tests#93]
### Acceptance Criteria

- [x] Upgrade version of the web3j plugin

**Comment by dolanor** [comment]
Should we upgrade the solidity compiler version as well?

**Comment by nmvalera** [comment]
Changing the `solc` version makes some unit tests break (because of gas estimation) so let's not change for now and keep this for a separate PR.

**Comment by ricardolyn** [comment]
by upgrading to the last web3 maven plugin, it should automatically download the right solc. but yes, we should keep the same version for now on the contracts.
